Using gpu device 0: Tesla K20m (CNMeM is disabled, CuDNN not available)
/home/rqiao/Theano/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
Building network ...
Traceback (most recent call last):
  File "./recurrent.py", line 132, in <module>
    main()
  File "./recurrent.py", line 75, in main
    loss = lasagne.objectives.categorical_crossentropy(prediction, target_values)
  File "/home/rqiao/Lasagne/lasagne/objectives.py", line 146, in categorical_crossentropy
    return theano.tensor.nnet.categorical_crossentropy(predictions, targets)
  File "/home/rqiao/Theano/theano/tensor/nnet/nnet.py", line 2071, in categorical_crossentropy
    return crossentropy_categorical_1hot(coding_dist, true_dist)
  File "/home/rqiao/Theano/theano/gof/op.py", line 611, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/rqiao/Theano/theano/tensor/nnet/nnet.py", line 1434, in make_node
    tensor.lvector))
TypeError: integer vector required for argument: true_one_of_n(got type: TensorType(float32, vector) instead of: TensorType(int64, vector))
INFO (theano.gof.compilelock): Waiting for existing lock by process '24568' (I am process '22071')
INFO (theano.gof.compilelock): To manually release the lock, delete /home/rqiao/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.6-Final-x86_64-2.7.5-64/lock_dir
